"""empty message

Revision ID: 48412b6e96b9
Revises: 76fe0679a8db
Create Date: 2020-10-24 02:07:12.450451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48412b6e96b9'
down_revision = '76fe0679a8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
